-- =============================================================================
--  LRMS — Loan Recovery Management System
--  COMPLETE INSTALLATION — import this one file and the application is ready.
--
--  Generated by database/build-install-sql.php. Do not edit by hand: it is
--  rebuilt from schema.sql and seed.php, which are the source of truth.
--
--  WHAT IT CONTAINS
--    * all 40 tables
--    * the three roles, the 14 report types and the default settings
--    * the customer visit form, the KRM OTS and CKCC OD-2 field visit
--      verification report forms, and the BC Supervisor inspection form
--    * one Admin/Supervisor account
--
--  HOW TO IMPORT (no command line needed)
--    1. Create an empty database in your hosting panel.
--    2. Open phpMyAdmin and SELECT that database on the left.
--    3. Import tab -> choose this file -> Go.
--
--  FIRST SIGN-IN
--    username: admin
--    password: ChangeMe@123
--
--    >> This password is published in the source code. The application forces a
--    >> change at first sign-in; do that immediately, before anyone else does.
--
--  IT DOES NOT CONTAIN
--    No CREATE DATABASE and no USE, so it imports into whichever database is
--    selected. No demo data. Re-importing DROPS the tables and starts over,
--    which destroys everything already recorded.
-- =============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';

/*M!999999\- enable the sandbox mode */ 
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `account_assignments`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `account_assignments` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `loan_account_id` bigint(20) unsigned NOT NULL,
  `bc_supervisor_id` bigint(20) unsigned NOT NULL,
  `branch_id` bigint(20) unsigned NOT NULL,
  `method` enum('excel_bc_code','auto_balance','manual','reassign') NOT NULL DEFAULT 'manual',
  `reason` varchar(255) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT 1,
  `assigned_by` bigint(20) unsigned DEFAULT NULL,
  `assigned_at` datetime DEFAULT NULL,
  `unassigned_by` bigint(20) unsigned DEFAULT NULL,
  `unassigned_at` datetime DEFAULT NULL,
  `excel_import_id` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_assignment_active` (`loan_account_id`,`is_active`),
  KEY `ix_assignments_bc` (`bc_supervisor_id`),
  KEY `ix_assignments_branch` (`branch_id`),
  KEY `ix_assignments_active` (`is_active`),
  KEY `fk_assign_by` (`assigned_by`),
  CONSTRAINT `fk_assign_account` FOREIGN KEY (`loan_account_id`) REFERENCES `loan_accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_assign_bc` FOREIGN KEY (`bc_supervisor_id`) REFERENCES `bc_supervisors` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_assign_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_assign_by` FOREIGN KEY (`assigned_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `api_tokens`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `api_tokens` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `device_id` bigint(20) unsigned DEFAULT NULL,
  `name` varchar(80) NOT NULL DEFAULT 'android',
  `token_hash` char(64) NOT NULL,
  `last_used_at` datetime DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `revoked_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_tokens_hash` (`token_hash`),
  KEY `ix_tokens_user` (`user_id`),
  KEY `fk_tokens_device` (`device_id`),
  CONSTRAINT `fk_tokens_device` FOREIGN KEY (`device_id`) REFERENCES `devices` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_tokens_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `attendance`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `attendance` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `bc_supervisor_id` bigint(20) unsigned NOT NULL,
  `branch_id` bigint(20) unsigned NOT NULL,
  `attendance_date` date NOT NULL,
  `check_in_at` datetime DEFAULT NULL,
  `check_in_lat` decimal(10,7) DEFAULT NULL,
  `check_in_lng` decimal(10,7) DEFAULT NULL,
  `check_in_accuracy` decimal(8,2) DEFAULT NULL,
  `check_in_address` varchar(255) DEFAULT NULL,
  `selfie_path` varchar(255) DEFAULT NULL,
  `check_out_at` datetime DEFAULT NULL,
  `check_out_lat` decimal(10,7) DEFAULT NULL,
  `check_out_lng` decimal(10,7) DEFAULT NULL,
  `check_out_accuracy` decimal(8,2) DEFAULT NULL,
  `check_out_address` varchar(255) DEFAULT NULL,
  `working_minutes` int(10) unsigned NOT NULL DEFAULT 0,
  `visits_count` int(10) unsigned NOT NULL DEFAULT 0,
  `status` enum('present','half_day','absent','leave','holiday') NOT NULL DEFAULT 'present',
  `remarks` varchar(255) DEFAULT NULL,
  `device_id` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_attendance_uuid` (`uuid`),
  UNIQUE KEY `uq_attendance_day` (`bc_supervisor_id`,`attendance_date`),
  KEY `ix_attendance_branch_date` (`branch_id`,`attendance_date`),
  KEY `fk_attendance_user` (`user_id`),
  KEY `fk_attendance_device` (`device_id`),
  CONSTRAINT `fk_attendance_bc` FOREIGN KEY (`bc_supervisor_id`) REFERENCES `bc_supervisors` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_attendance_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `fk_attendance_device` FOREIGN KEY (`device_id`) REFERENCES `devices` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_attendance_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `audit_logs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `audit_logs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `user_name` varchar(160) DEFAULT NULL,
  `role_slug` varchar(40) DEFAULT NULL,
  `action` varchar(80) NOT NULL,
  `entity_type` varchar(60) DEFAULT NULL,
  `entity_id` bigint(20) unsigned DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `old_values` longtext DEFAULT NULL,
  `new_values` longtext DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `device_id` bigint(20) unsigned DEFAULT NULL,
  `request_method` varchar(10) DEFAULT NULL,
  `request_path` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_audit_user` (`user_id`),
  KEY `ix_audit_action` (`action`),
  KEY `ix_audit_entity` (`entity_type`,`entity_id`),
  KEY `ix_audit_created` (`created_at`),
  CONSTRAINT `fk_audit_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `bc_supervisors`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `bc_supervisors` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `branch_id` bigint(20) unsigned NOT NULL,
  `bc_code` varchar(60) NOT NULL,
  `sp_cbc_name` varchar(190) DEFAULT NULL,
  `ssa` varchar(160) DEFAULT NULL,
  `iibf_number` varchar(60) DEFAULT NULL,
  `dra_id` varchar(60) DEFAULT NULL,
  `designation` varchar(120) DEFAULT NULL,
  `aadhaar_last4` char(4) DEFAULT NULL,
  `pan_number` varchar(12) DEFAULT NULL,
  `mobile` varchar(20) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `village` varchar(120) DEFAULT NULL,
  `block` varchar(120) DEFAULT NULL,
  `tehsil` varchar(120) DEFAULT NULL,
  `district` varchar(120) DEFAULT NULL,
  `state` varchar(120) DEFAULT NULL,
  `pincode` varchar(12) DEFAULT NULL,
  `joined_on` date DEFAULT NULL,
  `status` enum('active','inactive','suspended') NOT NULL DEFAULT 'active',
  `notes` varchar(255) DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_bc_user` (`user_id`),
  UNIQUE KEY `uq_bc_code` (`bc_code`),
  KEY `ix_bc_branch` (`branch_id`),
  KEY `ix_bc_status` (`status`),
  KEY `ix_bc_iibf` (`iibf_number`),
  KEY `ix_bc_dra` (`dra_id`),
  CONSTRAINT `fk_bc_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `fk_bc_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `branch_managers`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `branch_managers` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `branch_id` bigint(20) unsigned NOT NULL,
  `designation` varchar(120) DEFAULT NULL,
  `contact_number` varchar(20) DEFAULT NULL,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `assigned_at` datetime DEFAULT NULL,
  `assigned_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_branch_managers_user` (`user_id`),
  KEY `ix_branch_managers_branch` (`branch_id`),
  CONSTRAINT `fk_bm_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_bm_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `branches`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `branches` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(40) NOT NULL,
  `name` varchar(160) NOT NULL,
  `region` varchar(120) DEFAULT NULL,
  `zone` varchar(120) DEFAULT NULL,
  `district` varchar(120) DEFAULT NULL,
  `state` varchar(120) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `pincode` varchar(12) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `email` varchar(160) DEFAULT NULL,
  `latitude` decimal(10,7) DEFAULT NULL,
  `longitude` decimal(10,7) DEFAULT NULL,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_branches_code` (`code`),
  KEY `ix_branches_status` (`status`),
  KEY `ix_branches_name` (`name`),
  KEY `fk_branches_created_by` (`created_by`),
  CONSTRAINT `fk_branches_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `ckcc_renewals`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `ckcc_renewals` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `loan_account_id` bigint(20) unsigned NOT NULL,
  `branch_id` bigint(20) unsigned NOT NULL,
  `bc_supervisor_id` bigint(20) unsigned DEFAULT NULL,
  `visit_id` bigint(20) unsigned DEFAULT NULL,
  `loan_type` varchar(120) DEFAULT NULL,
  `limit_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `outstanding` decimal(15,2) NOT NULL DEFAULT 0.00,
  `overdue` decimal(15,2) NOT NULL DEFAULT 0.00,
  `renewal_eligible` tinyint(1) DEFAULT NULL,
  `renewal_due_bucket` enum('within_30_days','within_15_days','within_7_days','overdue') DEFAULT NULL,
  `renewal_due_date` date DEFAULT NULL,
  `expected_npa_date` date DEFAULT NULL,
  `days_remaining` int(11) DEFAULT NULL,
  `kyc_status` enum('complete','pending') DEFAULT NULL,
  `aadhaar_seeded` tinyint(1) DEFAULT NULL,
  `mobile_linked` tinyint(1) DEFAULT NULL,
  `aadhaar_authentication` enum('completed','pending') DEFAULT NULL,
  `renewal_consent` tinyint(1) DEFAULT NULL,
  `renewal_form_signed` tinyint(1) DEFAULT NULL,
  `biometrics_completed` tinyint(1) DEFAULT NULL,
  `renewal_status` enum('pending','documents_awaited','submitted','renewed','rejected','not_eligible','closed') NOT NULL DEFAULT 'pending',
  `visit_date` date DEFAULT NULL,
  `customer_availability` enum('available','not_available','shifted','deceased','refused') DEFAULT NULL,
  `documents_status` enum('complete','partial','pending','not_submitted') NOT NULL DEFAULT 'pending',
  `documents_remarks` varchar(500) DEFAULT NULL,
  `renewed_on` date DEFAULT NULL,
  `recommendation` enum('renew_immediately','documents_complete','documents_pending','customer_not_interested','branch_followup_required') DEFAULT NULL,
  `final_status` enum('customer_contacted','customer_verified','documents_collected','renewal_submitted','renewal_approved','pending_at_branch','became_npa','followup_required') DEFAULT NULL,
  `remarks` varchar(500) DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_ckcc_account` (`loan_account_id`),
  KEY `ix_ckcc_branch` (`branch_id`),
  KEY `ix_ckcc_status` (`renewal_status`),
  KEY `ix_ckcc_bc` (`bc_supervisor_id`),
  KEY `ix_ckcc_final` (`final_status`),
  KEY `ix_ckcc_due` (`renewal_due_date`),
  KEY `fk_ckcc_visit` (`visit_id`),
  CONSTRAINT `fk_ckcc_account` FOREIGN KEY (`loan_account_id`) REFERENCES `loan_accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ckcc_bc` FOREIGN KEY (`bc_supervisor_id`) REFERENCES `bc_supervisors` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_ckcc_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `fk_ckcc_visit` FOREIGN KEY (`visit_id`) REFERENCES `visits` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `devices`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `devices` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `device_uuid` varchar(120) NOT NULL,
  `model` varchar(120) DEFAULT NULL,
  `manufacturer` varchar(120) DEFAULT NULL,
  `os_version` varchar(60) DEFAULT NULL,
  `app_version` varchar(40) DEFAULT NULL,
  `fcm_token` varchar(255) DEFAULT NULL,
  `status` enum('active','blocked','unbound') NOT NULL DEFAULT 'active',
  `bound_at` datetime DEFAULT NULL,
  `last_seen_at` datetime DEFAULT NULL,
  `last_ip` varchar(45) DEFAULT NULL,
  `last_latitude` decimal(10,7) DEFAULT NULL,
  `last_longitude` decimal(10,7) DEFAULT NULL,
  `last_location_at` datetime DEFAULT NULL,
  `last_address` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_devices_uuid` (`device_uuid`),
  KEY `ix_devices_user` (`user_id`),
  KEY `ix_devices_status` (`status`),
  CONSTRAINT `fk_devices_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `documents`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `documents` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `owner_type` enum('loan_account','visit','inspection','user','branch','import') NOT NULL,
  `owner_id` bigint(20) unsigned NOT NULL,
  `title` varchar(190) NOT NULL,
  `doc_type` varchar(60) DEFAULT NULL,
  `file_path` varchar(255) NOT NULL,
  `file_name` varchar(190) NOT NULL,
  `mime_type` varchar(80) DEFAULT NULL,
  `file_size` bigint(20) unsigned NOT NULL DEFAULT 0,
  `sha256` char(64) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `uploaded_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_documents_owner` (`owner_type`,`owner_id`),
  KEY `fk_documents_user` (`uploaded_by`),
  CONSTRAINT `fk_documents_user` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `excel_import_errors`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `excel_import_errors` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `import_id` bigint(20) unsigned NOT NULL,
  `row_number` int(10) unsigned NOT NULL,
  `column_name` varchar(160) DEFAULT NULL,
  `account_number` varchar(60) DEFAULT NULL,
  `error_type` enum('missing_required','invalid_data','duplicate','unknown_branch','invalid_bc','other') NOT NULL DEFAULT 'other',
  `severity` enum('error','warning') NOT NULL DEFAULT 'error',
  `message` varchar(255) NOT NULL,
  `raw_row` longtext DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_import_errors_import` (`import_id`),
  KEY `ix_import_errors_type` (`error_type`),
  CONSTRAINT `fk_import_errors_import` FOREIGN KEY (`import_id`) REFERENCES `excel_imports` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `excel_imports`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `excel_imports` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `original_name` varchar(255) NOT NULL,
  `stored_path` varchar(255) NOT NULL,
  `file_size` bigint(20) unsigned NOT NULL DEFAULT 0,
  `sha256` char(64) DEFAULT NULL,
  `sheet_name` varchar(160) DEFAULT NULL,
  `header_row` int(10) unsigned NOT NULL DEFAULT 1,
  `detected_headers` longtext DEFAULT NULL,
  `mapping` longtext DEFAULT NULL,
  `template_id` bigint(20) unsigned DEFAULT NULL,
  `status` enum('uploaded','mapped','importing','completed','failed','cancelled') NOT NULL DEFAULT 'uploaded',
  `total_rows` int(10) unsigned NOT NULL DEFAULT 0,
  `imported_rows` int(10) unsigned NOT NULL DEFAULT 0,
  `created_accounts` int(10) unsigned NOT NULL DEFAULT 0,
  `updated_accounts` int(10) unsigned NOT NULL DEFAULT 0,
  `skipped_rows` int(10) unsigned NOT NULL DEFAULT 0,
  `error_rows` int(10) unsigned NOT NULL DEFAULT 0,
  `duplicate_rows` int(10) unsigned NOT NULL DEFAULT 0,
  `assigned_rows` int(10) unsigned NOT NULL DEFAULT 0,
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `error_message` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_imports_user` (`user_id`),
  KEY `ix_imports_status` (`status`),
  KEY `fk_imports_template` (`template_id`),
  CONSTRAINT `fk_imports_template` FOREIGN KEY (`template_id`) REFERENCES `excel_mapping_templates` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_imports_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `excel_mapping_templates`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `excel_mapping_templates` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(160) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `mapping` longtext NOT NULL,
  `header_row` int(10) unsigned NOT NULL DEFAULT 1,
  `usage_count` int(10) unsigned NOT NULL DEFAULT 0,
  `last_used_at` datetime DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_mapping_name` (`name`),
  KEY `fk_mapping_user` (`created_by`),
  CONSTRAINT `fk_mapping_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `followups`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `followups` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) NOT NULL,
  `loan_account_id` bigint(20) unsigned NOT NULL,
  `visit_id` bigint(20) unsigned DEFAULT NULL,
  `promise_id` bigint(20) unsigned DEFAULT NULL,
  `bc_supervisor_id` bigint(20) unsigned DEFAULT NULL,
  `branch_id` bigint(20) unsigned NOT NULL,
  `followup_date` date NOT NULL,
  `action` enum('call','visit','notice','legal','other') NOT NULL DEFAULT 'visit',
  `notes` varchar(500) DEFAULT NULL,
  `status` enum('pending','done','cancelled') NOT NULL DEFAULT 'pending',
  `completed_at` datetime DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_followups_uuid` (`uuid`),
  KEY `ix_followups_account` (`loan_account_id`),
  KEY `ix_followups_bc_date` (`bc_supervisor_id`,`followup_date`),
  KEY `ix_followups_branch_date` (`branch_id`,`followup_date`),
  KEY `ix_followups_status` (`status`),
  KEY `fk_followups_visit` (`visit_id`),
  KEY `fk_followups_promise` (`promise_id`),
  CONSTRAINT `fk_followups_account` FOREIGN KEY (`loan_account_id`) REFERENCES `loan_accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_followups_bc` FOREIGN KEY (`bc_supervisor_id`) REFERENCES `bc_supervisors` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_followups_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `fk_followups_promise` FOREIGN KEY (`promise_id`) REFERENCES `promises` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_followups_visit` FOREIGN KEY (`visit_id`) REFERENCES `visits` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `inspection_form_fields`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `inspection_form_fields` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `form_id` bigint(20) unsigned NOT NULL,
  `field_key` varchar(80) NOT NULL,
  `label` varchar(255) NOT NULL,
  `field_type` enum('section','text','textarea','number','decimal','date','time','dropdown','radio','checkbox','yes_no','photo','signature','gps','remarks') NOT NULL DEFAULT 'text',
  `options` text DEFAULT NULL,
  `placeholder` varchar(160) DEFAULT NULL,
  `help_text` varchar(2000) DEFAULT NULL,
  `is_required` tinyint(1) NOT NULL DEFAULT 0,
  `min_value` decimal(15,2) DEFAULT NULL,
  `max_value` decimal(15,2) DEFAULT NULL,
  `max_length` int(10) unsigned DEFAULT NULL,
  `sort_order` int(10) unsigned NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `condition_field_id` bigint(20) unsigned DEFAULT NULL,
  `condition_operator` enum('equals','not_equals','in','contains','filled','empty') DEFAULT NULL,
  `condition_value` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_inspection_field_key` (`form_id`,`field_key`),
  KEY `ix_inspection_fields_order` (`form_id`,`sort_order`),
  KEY `fk_insp_fields_condition` (`condition_field_id`),
  CONSTRAINT `fk_insp_fields_condition` FOREIGN KEY (`condition_field_id`) REFERENCES `inspection_form_fields` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_insp_fields_form` FOREIGN KEY (`form_id`) REFERENCES `inspection_forms` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `inspection_form_fields` (`id`, `form_id`, `field_key`, `label`, `field_type`, `options`, `placeholder`, `help_text`, `is_required`, `min_value`, `max_value`, `max_length`, `sort_order`, `is_active`, `condition_field_id`, `condition_operator`, `condition_value`, `created_at`, `updated_at`) VALUES (1,1,'bc_visited_customer','Did the BC Supervisor visit the customer?','yes_no',NULL,NULL,NULL,1,NULL,NULL,NULL,10,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(2,1,'customer_available','Was the customer available?','yes_no',NULL,NULL,NULL,1,NULL,NULL,NULL,20,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(3,1,'customer_contacted','Was the customer contacted?','yes_no',NULL,NULL,NULL,1,NULL,NULL,NULL,30,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(4,1,'location_correct','Was the location correct?','yes_no',NULL,NULL,'Compare with the address on the account.',1,NULL,NULL,NULL,40,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(5,1,'gps_verified','Was the visit GPS verified?','yes_no',NULL,NULL,'The system shows the distance between your point and the BC Supervisor point.',1,NULL,NULL,NULL,50,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(6,1,'photos_taken','Were the required photographs taken?','yes_no',NULL,NULL,NULL,1,NULL,NULL,NULL,60,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(7,1,'information_correct','Was the information recorded correctly?','yes_no',NULL,NULL,NULL,1,NULL,NULL,NULL,70,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(8,1,'recovery_recorded_correctly','Was recovery / promise information correctly recorded?','yes_no',NULL,NULL,NULL,1,NULL,NULL,NULL,80,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(9,1,'customer_confirmation','What did the customer confirm?','dropdown','Confirmed the visit\nDenied the visit\nCould not recall\nCustomer not available',NULL,NULL,0,NULL,NULL,NULL,90,1,1,'equals','Yes','2026-08-19 07:56:34','2026-08-19 07:56:34'),
(10,1,'followup_required','Is follow-up required?','yes_no',NULL,NULL,NULL,1,NULL,NULL,NULL,100,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(11,1,'inspector_remarks','Inspector remarks','remarks',NULL,NULL,NULL,1,NULL,NULL,NULL,110,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34');
DROP TABLE IF EXISTS `inspection_form_values`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `inspection_form_values` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `inspection_id` bigint(20) unsigned NOT NULL,
  `field_id` bigint(20) unsigned DEFAULT NULL,
  `field_key` varchar(80) NOT NULL,
  `label` varchar(255) DEFAULT NULL,
  `field_type` varchar(30) DEFAULT NULL,
  `value` text DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_inspection_value` (`inspection_id`,`field_key`),
  KEY `ix_insp_values_field` (`field_id`),
  CONSTRAINT `fk_insp_values_field` FOREIGN KEY (`field_id`) REFERENCES `inspection_form_fields` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_insp_values_inspection` FOREIGN KEY (`inspection_id`) REFERENCES `inspections` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `inspection_forms`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `inspection_forms` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(160) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `version` int(10) unsigned NOT NULL DEFAULT 1,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `is_default` tinyint(1) NOT NULL DEFAULT 0,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_inspection_forms_active` (`is_active`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `inspection_forms` (`id`, `name`, `description`, `version`, `is_active`, `is_default`, `created_by`, `created_at`, `updated_at`) VALUES (1,'BC Supervisor Field Work Inspection','Default TYPE B form: Admin/Supervisor verification that the BC Supervisor performed the allocated field work correctly.',1,1,1,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34');
DROP TABLE IF EXISTS `inspection_gps`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `inspection_gps` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `inspection_id` bigint(20) unsigned NOT NULL,
  `event` enum('start','form','photo','submit') NOT NULL DEFAULT 'start',
  `latitude` decimal(10,7) NOT NULL,
  `longitude` decimal(10,7) NOT NULL,
  `accuracy` decimal(8,2) DEFAULT NULL,
  `provider` varchar(40) DEFAULT NULL,
  `is_mock` tinyint(1) NOT NULL DEFAULT 0,
  `address` varchar(255) DEFAULT NULL,
  `captured_at` datetime DEFAULT NULL,
  `server_time` datetime DEFAULT NULL,
  `is_valid` tinyint(1) NOT NULL DEFAULT 1,
  `validation_note` varchar(255) DEFAULT NULL,
  `distance_to_visit_metres` decimal(10,2) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_insp_gps_inspection` (`inspection_id`,`event`),
  CONSTRAINT `fk_insp_gps_inspection` FOREIGN KEY (`inspection_id`) REFERENCES `inspections` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `inspection_photos`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `inspection_photos` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `inspection_id` bigint(20) unsigned NOT NULL,
  `photo_type` enum('bc_supervisor','customer','location','document','selfie','other') NOT NULL DEFAULT 'other',
  `file_path` varchar(255) NOT NULL,
  `file_name` varchar(190) NOT NULL,
  `mime_type` varchar(60) NOT NULL DEFAULT 'image/jpeg',
  `file_size` bigint(20) unsigned NOT NULL DEFAULT 0,
  `width` int(10) unsigned DEFAULT NULL,
  `height` int(10) unsigned DEFAULT NULL,
  `sha256` char(64) DEFAULT NULL,
  `latitude` decimal(10,7) DEFAULT NULL,
  `longitude` decimal(10,7) DEFAULT NULL,
  `accuracy` decimal(8,2) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `captured_at` datetime DEFAULT NULL,
  `watermarked` tinyint(1) NOT NULL DEFAULT 0,
  `caption` varchar(255) DEFAULT NULL,
  `uploaded_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_insp_photos_inspection` (`inspection_id`,`photo_type`),
  CONSTRAINT `fk_insp_photos_inspection` FOREIGN KEY (`inspection_id`) REFERENCES `inspections` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `inspections`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `inspections` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) NOT NULL,
  `admin_user_id` bigint(20) unsigned NOT NULL,
  `bc_supervisor_id` bigint(20) unsigned NOT NULL,
  `branch_id` bigint(20) unsigned NOT NULL,
  `loan_account_id` bigint(20) unsigned DEFAULT NULL,
  `visit_id` bigint(20) unsigned DEFAULT NULL,
  `form_id` bigint(20) unsigned DEFAULT NULL,
  `inspection_date` date NOT NULL,
  `started_at` datetime DEFAULT NULL,
  `submitted_at` datetime DEFAULT NULL,
  `result` enum('work_verified','partially_verified','not_satisfactory','customer_not_found','bc_not_present','visit_not_genuine','incorrect_information','gps_issue','photo_issue','other') DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `followup_required` tinyint(1) NOT NULL DEFAULT 0,
  `status` enum('draft','submitted') NOT NULL DEFAULT 'draft',
  `gps_verified` tinyint(1) NOT NULL DEFAULT 0,
  `photo_count` int(10) unsigned NOT NULL DEFAULT 0,
  `inspector_signature` varchar(255) DEFAULT NULL,
  `bc_signature` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_inspections_uuid` (`uuid`),
  KEY `ix_inspections_bc_date` (`bc_supervisor_id`,`inspection_date`),
  KEY `ix_inspections_branch_date` (`branch_id`,`inspection_date`),
  KEY `ix_inspections_admin` (`admin_user_id`),
  KEY `ix_inspections_visit` (`visit_id`),
  KEY `ix_inspections_result` (`result`),
  KEY `fk_insp_account` (`loan_account_id`),
  KEY `fk_insp_form` (`form_id`),
  CONSTRAINT `fk_insp_account` FOREIGN KEY (`loan_account_id`) REFERENCES `loan_accounts` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_insp_admin` FOREIGN KEY (`admin_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_insp_bc` FOREIGN KEY (`bc_supervisor_id`) REFERENCES `bc_supervisors` (`id`),
  CONSTRAINT `fk_insp_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `fk_insp_form` FOREIGN KEY (`form_id`) REFERENCES `inspection_forms` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_insp_visit` FOREIGN KEY (`visit_id`) REFERENCES `visits` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `krm_ots_cases`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `krm_ots_cases` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `loan_account_id` bigint(20) unsigned NOT NULL,
  `branch_id` bigint(20) unsigned NOT NULL,
  `bc_supervisor_id` bigint(20) unsigned DEFAULT NULL,
  `visit_id` bigint(20) unsigned DEFAULT NULL,
  `ots_eligible` tinyint(1) DEFAULT NULL,
  `scheme` enum('krm_ots','general_ots','other') NOT NULL DEFAULT 'krm_ots',
  `scheme_other` varchar(120) DEFAULT NULL,
  `outstanding` decimal(15,2) NOT NULL DEFAULT 0.00,
  `ots_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `borrower_share` decimal(15,2) DEFAULT NULL,
  `initial_deposit_required` decimal(15,2) DEFAULT NULL,
  `sanctioned_amount` decimal(15,2) DEFAULT NULL,
  `paid_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `customer_response` enum('agreed','requested_time','financial_difficulty','refused','not_eligible') DEFAULT NULL,
  `ots_status` enum('proposed','under_review','approved','rejected','partly_paid','paid','closed','cancelled') NOT NULL DEFAULT 'proposed',
  `visit_date` date DEFAULT NULL,
  `promise_date` date DEFAULT NULL,
  `recommendation` enum('proposal_recommended','followup_required','customer_refused','not_eligible') DEFAULT NULL,
  `final_status` enum('customer_contacted','customer_verified','ots_accepted','ots_rejected','initial_deposit_received','ots_closed','followup_required') DEFAULT NULL,
  `remarks` varchar(500) DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_krm_account` (`loan_account_id`),
  KEY `ix_krm_branch` (`branch_id`),
  KEY `ix_krm_status` (`ots_status`),
  KEY `ix_krm_bc` (`bc_supervisor_id`),
  KEY `ix_krm_final` (`final_status`),
  KEY `ix_krm_response` (`customer_response`),
  KEY `fk_krm_visit` (`visit_id`),
  CONSTRAINT `fk_krm_account` FOREIGN KEY (`loan_account_id`) REFERENCES `loan_accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_krm_bc` FOREIGN KEY (`bc_supervisor_id`) REFERENCES `bc_supervisors` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_krm_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `fk_krm_visit` FOREIGN KEY (`visit_id`) REFERENCES `visits` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `loan_accounts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `loan_accounts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `account_number` varchar(60) NOT NULL,
  `cif` varchar(60) DEFAULT NULL,
  `borrower_name` varchar(190) NOT NULL,
  `father_name` varchar(190) DEFAULT NULL,
  `mobile` varchar(20) DEFAULT NULL,
  `gender` enum('male','female','other') DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `alternate_mobile` varchar(20) DEFAULT NULL,
  `aadhaar_last4` char(4) DEFAULT NULL,
  `pan_number` varchar(12) DEFAULT NULL,
  `village` varchar(160) DEFAULT NULL,
  `gram_panchayat` varchar(160) DEFAULT NULL,
  `tehsil` varchar(120) DEFAULT NULL,
  `district` varchar(120) DEFAULT NULL,
  `state` varchar(120) DEFAULT NULL,
  `pincode` varchar(12) DEFAULT NULL,
  `address` varchar(500) DEFAULT NULL,
  `branch_id` bigint(20) unsigned NOT NULL,
  `branch_code_raw` varchar(60) DEFAULT NULL,
  `bc_code_raw` varchar(60) DEFAULT NULL,
  `loan_type` varchar(120) DEFAULT NULL,
  `sanction_date` date DEFAULT NULL,
  `npa_date` date DEFAULT NULL,
  `limit_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `drawing_power` decimal(15,2) DEFAULT NULL,
  `outstanding` decimal(15,2) NOT NULL DEFAULT 0.00,
  `interest_overdue` decimal(15,2) DEFAULT NULL,
  `overdue` decimal(15,2) NOT NULL DEFAULT 0.00,
  `total_recovered` decimal(15,2) NOT NULL DEFAULT 0.00,
  `asset_classification` enum('standard','sma_0','sma_1','sma_2','npa') DEFAULT NULL,
  `loan_category` enum('general','krm_ots','ckcc_od2') NOT NULL DEFAULT 'general',
  `status` enum('active','closed','settled','written_off','excluded') NOT NULL DEFAULT 'active',
  `recovery_status` enum('pending','in_progress','partly_recovered','recovered','ptp','ots','not_traceable') NOT NULL DEFAULT 'pending',
  `visit_count` int(10) unsigned NOT NULL DEFAULT 0,
  `last_visit_at` datetime DEFAULT NULL,
  `excel_import_id` bigint(20) unsigned DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_accounts_number` (`account_number`),
  KEY `ix_accounts_branch` (`branch_id`),
  KEY `ix_accounts_cif` (`cif`),
  KEY `ix_accounts_mobile` (`mobile`),
  KEY `ix_accounts_borrower` (`borrower_name`),
  KEY `ix_accounts_village` (`village`),
  KEY `ix_accounts_category` (`loan_category`),
  KEY `ix_accounts_status` (`status`),
  KEY `ix_accounts_npa` (`npa_date`),
  KEY `ix_accounts_asset_class` (`asset_classification`),
  KEY `ix_accounts_import` (`excel_import_id`),
  KEY `fk_accounts_created_by` (`created_by`),
  CONSTRAINT `fk_accounts_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `fk_accounts_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_accounts_import` FOREIGN KEY (`excel_import_id`) REFERENCES `excel_imports` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `notifications`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `notifications` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `role_slug` varchar(40) DEFAULT NULL,
  `branch_id` bigint(20) unsigned DEFAULT NULL,
  `title` varchar(190) NOT NULL,
  `body` varchar(500) DEFAULT NULL,
  `type` enum('info','warning','alert','deadline','assignment','approval','inspection') NOT NULL DEFAULT 'info',
  `link` varchar(255) DEFAULT NULL,
  `related_type` varchar(60) DEFAULT NULL,
  `related_id` bigint(20) unsigned DEFAULT NULL,
  `is_read` tinyint(1) NOT NULL DEFAULT 0,
  `read_at` datetime DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_notifications_user` (`user_id`,`is_read`),
  KEY `ix_notifications_role` (`role_slug`),
  KEY `ix_notifications_branch` (`branch_id`),
  CONSTRAINT `fk_notifications_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_notifications_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `otp_codes`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `otp_codes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `purpose` enum('login','password_reset','late_approval') NOT NULL DEFAULT 'login',
  `code_hash` char(64) NOT NULL,
  `channel` enum('sms','email','log') NOT NULL DEFAULT 'sms',
  `destination` varchar(190) DEFAULT NULL,
  `attempts` int(10) unsigned NOT NULL DEFAULT 0,
  `expires_at` datetime NOT NULL,
  `consumed_at` datetime DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_otp_user` (`user_id`,`purpose`),
  KEY `ix_otp_expires` (`expires_at`),
  CONSTRAINT `fk_otp_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `promises`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `promises` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) NOT NULL,
  `loan_account_id` bigint(20) unsigned NOT NULL,
  `visit_id` bigint(20) unsigned DEFAULT NULL,
  `bc_supervisor_id` bigint(20) unsigned DEFAULT NULL,
  `branch_id` bigint(20) unsigned NOT NULL,
  `promise_amount` decimal(15,2) NOT NULL,
  `promise_date` date NOT NULL,
  `followup_date` date DEFAULT NULL,
  `remarks` varchar(500) DEFAULT NULL,
  `status` enum('pending','kept','partially_kept','broken','cancelled') NOT NULL DEFAULT 'pending',
  `kept_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `closed_at` datetime DEFAULT NULL,
  `closed_by` bigint(20) unsigned DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_promises_uuid` (`uuid`),
  KEY `ix_promises_account` (`loan_account_id`),
  KEY `ix_promises_bc` (`bc_supervisor_id`),
  KEY `ix_promises_branch_date` (`branch_id`,`promise_date`),
  KEY `ix_promises_status` (`status`),
  KEY `fk_promises_visit` (`visit_id`),
  CONSTRAINT `fk_promises_account` FOREIGN KEY (`loan_account_id`) REFERENCES `loan_accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_promises_bc` FOREIGN KEY (`bc_supervisor_id`) REFERENCES `bc_supervisors` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_promises_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `fk_promises_visit` FOREIGN KEY (`visit_id`) REFERENCES `visits` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `recoveries`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `recoveries` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) NOT NULL,
  `loan_account_id` bigint(20) unsigned NOT NULL,
  `visit_id` bigint(20) unsigned DEFAULT NULL,
  `bc_supervisor_id` bigint(20) unsigned DEFAULT NULL,
  `branch_id` bigint(20) unsigned NOT NULL,
  `amount` decimal(15,2) NOT NULL,
  `recovery_date` date NOT NULL,
  `payment_mode` varchar(40) NOT NULL DEFAULT 'Cash',
  `receipt_number` varchar(80) DEFAULT NULL,
  `remarks` varchar(500) DEFAULT NULL,
  `status` enum('recorded','verified','rejected') NOT NULL DEFAULT 'recorded',
  `verified_by` bigint(20) unsigned DEFAULT NULL,
  `verified_at` datetime DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_recoveries_uuid` (`uuid`),
  KEY `ix_recoveries_account` (`loan_account_id`),
  KEY `ix_recoveries_bc_date` (`bc_supervisor_id`,`recovery_date`),
  KEY `ix_recoveries_branch_date` (`branch_id`,`recovery_date`),
  KEY `ix_recoveries_receipt` (`receipt_number`),
  KEY `fk_recoveries_visit` (`visit_id`),
  CONSTRAINT `fk_recoveries_account` FOREIGN KEY (`loan_account_id`) REFERENCES `loan_accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_recoveries_bc` FOREIGN KEY (`bc_supervisor_id`) REFERENCES `bc_supervisors` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_recoveries_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `fk_recoveries_visit` FOREIGN KEY (`visit_id`) REFERENCES `visits` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `report_exports`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `report_exports` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `report_type_id` bigint(20) unsigned DEFAULT NULL,
  `report_slug` varchar(60) NOT NULL,
  `format` enum('pdf','excel','csv') NOT NULL,
  `filters` longtext DEFAULT NULL,
  `file_path` varchar(255) DEFAULT NULL,
  `file_name` varchar(190) DEFAULT NULL,
  `file_size` bigint(20) unsigned NOT NULL DEFAULT 0,
  `row_count` int(10) unsigned NOT NULL DEFAULT 0,
  `status` enum('queued','completed','failed') NOT NULL DEFAULT 'queued',
  `error_message` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_exports_user` (`user_id`),
  KEY `ix_exports_slug` (`report_slug`),
  KEY `fk_exports_type` (`report_type_id`),
  CONSTRAINT `fk_exports_type` FOREIGN KEY (`report_type_id`) REFERENCES `report_types` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_exports_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `report_submissions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `report_submissions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `bc_supervisor_id` bigint(20) unsigned NOT NULL,
  `branch_id` bigint(20) unsigned NOT NULL,
  `report_type_id` bigint(20) unsigned NOT NULL,
  `report_date` date NOT NULL,
  `deadline_at` datetime NOT NULL,
  `submitted_at` datetime DEFAULT NULL,
  `is_late` tinyint(1) NOT NULL DEFAULT 0,
  `status` enum('pending','submitted','late_pending','late_approved','late_rejected','locked') NOT NULL DEFAULT 'pending',
  `visits_count` int(10) unsigned NOT NULL DEFAULT 0,
  `recovery_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `promises_count` int(10) unsigned NOT NULL DEFAULT 0,
  `summary` varchar(500) DEFAULT NULL,
  `late_reason` varchar(500) DEFAULT NULL,
  `approved_by` bigint(20) unsigned DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `approval_remarks` varchar(500) DEFAULT NULL,
  `device_id` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_submission_day` (`bc_supervisor_id`,`report_type_id`,`report_date`),
  KEY `ix_submissions_branch_date` (`branch_id`,`report_date`),
  KEY `ix_submissions_status` (`status`),
  KEY `fk_submissions_type` (`report_type_id`),
  KEY `fk_submissions_approver` (`approved_by`),
  CONSTRAINT `fk_submissions_approver` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_submissions_bc` FOREIGN KEY (`bc_supervisor_id`) REFERENCES `bc_supervisors` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_submissions_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `fk_submissions_type` FOREIGN KEY (`report_type_id`) REFERENCES `report_types` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `report_types`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `report_types` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `slug` varchar(60) NOT NULL,
  `name` varchar(120) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `is_daily` tinyint(1) NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `sort_order` int(10) unsigned NOT NULL DEFAULT 0,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_report_types_slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `report_types` (`id`, `slug`, `name`, `description`, `is_daily`, `is_active`, `sort_order`, `created_at`, `updated_at`) VALUES (1,'daily_field_report','Daily Field Report','The BC Supervisor day-end submission the report deadline applies to.',1,1,1,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(2,'customer_visit','Customer Visit Report','TYPE A — BC Supervisor customer recovery visits.',0,1,2,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(3,'bc_inspection','BC Supervisor Inspection Report','TYPE B — Admin/Supervisor verification of BC field work.',0,1,3,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(4,'krm_ots','KRM OTS Report','One Time Settlement tracking.',0,1,4,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(5,'ckcc_od2','CKCC OD-2 Renewal Report','CKCC OD-2 renewal tracking.',0,1,5,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(6,'recovery','Recovery Report','Amounts collected by mode, date, branch and supervisor.',0,1,6,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(7,'ptp','PTP Report','Promise to pay register and outcomes.',0,1,7,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(8,'followup','Follow-up Report','Pending and completed follow-up actions.',0,1,8,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(9,'attendance','Attendance Report','Check in/out, working hours and visits per day.',0,1,9,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(10,'gps','GPS Report','Captured coordinates, accuracy and validation results.',0,1,10,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(11,'photo','Photo Report','Photographic evidence captured in the field.',0,1,11,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(12,'target','Target Report','Target versus achievement with pending and percentage.',0,1,12,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(13,'branch_performance','Branch Performance','Branch level visits, recovery and coverage.',0,1,13,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(14,'bc_performance','BC Supervisor Performance','Supervisor level visits, recovery and inspection outcomes.',0,1,14,'2026-08-19 07:56:34','2026-08-19 07:56:34');
DROP TABLE IF EXISTS `roles`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `roles` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `slug` varchar(40) NOT NULL,
  `name` varchar(80) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_roles_slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `roles` (`id`, `slug`, `name`, `description`, `created_at`, `updated_at`) VALUES (1,'admin','Admin / Supervisor','Full control. Monitors and inspects BC Supervisors; does not perform customer recovery visits.','2026-08-19 07:56:34','2026-08-19 07:56:34'),
(2,'branch_manager','Branch Manager','Read and report access limited to their own branch.','2026-08-19 07:56:34','2026-08-19 07:56:34'),
(3,'bc_supervisor','BC Supervisor','Field officer. Performs customer recovery visits through the Android app.','2026-08-19 07:56:34','2026-08-19 07:56:34');
DROP TABLE IF EXISTS `sync_batches`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sync_batches` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `batch_uuid` char(36) NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `device_id` bigint(20) unsigned DEFAULT NULL,
  `direction` enum('push','pull') NOT NULL DEFAULT 'push',
  `items_received` int(10) unsigned NOT NULL DEFAULT 0,
  `items_accepted` int(10) unsigned NOT NULL DEFAULT 0,
  `items_duplicate` int(10) unsigned NOT NULL DEFAULT 0,
  `items_failed` int(10) unsigned NOT NULL DEFAULT 0,
  `app_version` varchar(40) DEFAULT NULL,
  `network_type` varchar(20) DEFAULT NULL,
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sync_batch_uuid` (`batch_uuid`),
  KEY `ix_sync_user` (`user_id`),
  CONSTRAINT `fk_sync_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `system_settings`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `system_settings` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `key` varchar(100) NOT NULL,
  `value` longtext DEFAULT NULL,
  `group` varchar(60) NOT NULL DEFAULT 'general',
  `updated_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_settings_key` (`key`),
  KEY `ix_settings_group` (`group`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `system_settings` (`id`, `key`, `value`, `group`, `updated_by`, `created_at`, `updated_at`) VALUES (1,'site_name','LRMS','general',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(2,'organisation_name','Loan Recovery Management System','general',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(3,'maintenance_mode','0','general',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(4,'supervisor_offline_minutes','15','general',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(5,'report_deadline_time','18:00','reports',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(6,'report_working_days','1,2,3,4,5,6','reports',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(7,'report_reminder_minutes','60,30,10','reports',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(8,'allow_late_submission_requests','1','reports',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(9,'min_visit_photos','1','field',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(10,'min_inspection_photos','1','field',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(11,'require_borrower_signature','0','field',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(12,'watermark_photos','1','field',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(13,'payment_modes','Cash,Bank Transfer,UPI,Cheque,Other','field',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(14,'gps_max_accuracy_metres','200','gps',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(15,'gps_max_drift_metres','0','gps',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(16,'gps_mock_location_allowed','0','gps',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(17,'otp_web_login','0','security',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(18,'otp_app_login','0','security',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(19,'device_binding','1','security',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(20,'api_token_ttl_days','30','security',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(21,'default_visit_form_id','1','forms',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(22,'default_inspection_form_id','1','forms',NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34');
DROP TABLE IF EXISTS `targets`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `targets` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `scope` enum('bc_supervisor','branch') NOT NULL DEFAULT 'bc_supervisor',
  `bc_supervisor_id` bigint(20) unsigned DEFAULT NULL,
  `branch_id` bigint(20) unsigned DEFAULT NULL,
  `period` enum('daily','monthly') NOT NULL DEFAULT 'daily',
  `period_start` date NOT NULL,
  `period_end` date NOT NULL,
  `visit_target` int(10) unsigned NOT NULL DEFAULT 0,
  `recovery_target` decimal(15,2) NOT NULL DEFAULT 0.00,
  `notes` varchar(255) DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_target_period` (`scope`,`bc_supervisor_id`,`branch_id`,`period`,`period_start`),
  KEY `ix_targets_branch` (`branch_id`),
  KEY `ix_targets_bc` (`bc_supervisor_id`),
  CONSTRAINT `fk_targets_bc` FOREIGN KEY (`bc_supervisor_id`) REFERENCES `bc_supervisors` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_targets_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `role_id` bigint(20) unsigned NOT NULL,
  `branch_id` bigint(20) unsigned DEFAULT NULL,
  `name` varchar(160) NOT NULL,
  `email` varchar(190) DEFAULT NULL,
  `username` varchar(80) DEFAULT NULL,
  `employee_code` varchar(60) DEFAULT NULL,
  `mobile` varchar(20) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `status` enum('active','inactive','suspended') NOT NULL DEFAULT 'active',
  `must_change_password` tinyint(1) NOT NULL DEFAULT 0,
  `failed_attempts` int(10) unsigned NOT NULL DEFAULT 0,
  `locked_until` datetime DEFAULT NULL,
  `last_login_at` datetime DEFAULT NULL,
  `last_login_ip` varchar(45) DEFAULT NULL,
  `password_changed_at` datetime DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_users_email` (`email`),
  UNIQUE KEY `uq_users_username` (`username`),
  UNIQUE KEY `uq_users_employee_code` (`employee_code`),
  KEY `ix_users_role` (`role_id`),
  KEY `ix_users_branch` (`branch_id`),
  KEY `ix_users_status` (`status`),
  CONSTRAINT `fk_users_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_users_role` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `users` (`id`, `role_id`, `branch_id`, `name`, `email`, `username`, `employee_code`, `mobile`, `password`, `status`, `must_change_password`, `failed_attempts`, `locked_until`, `last_login_at`, `last_login_ip`, `password_changed_at`, `created_by`, `created_at`, `updated_at`) VALUES (1,1,NULL,'System Administrator','admin@lrms.local','admin','ADM001',NULL,'$2y$12$pRKeeZ1oWzWnYR/s80Mi.enXIXKG1xAs96UUL0wXrKKD6StGTh/F2','active',1,0,NULL,NULL,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34');
DROP TABLE IF EXISTS `visit_form_fields`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `visit_form_fields` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `form_id` bigint(20) unsigned NOT NULL,
  `field_key` varchar(80) NOT NULL,
  `label` varchar(255) NOT NULL,
  `field_type` enum('section','text','textarea','number','decimal','date','time','dropdown','radio','checkbox','yes_no','photo','signature','gps','remarks') NOT NULL DEFAULT 'text',
  `options` text DEFAULT NULL,
  `placeholder` varchar(160) DEFAULT NULL,
  `help_text` varchar(2000) DEFAULT NULL,
  `is_required` tinyint(1) NOT NULL DEFAULT 0,
  `min_value` decimal(15,2) DEFAULT NULL,
  `max_value` decimal(15,2) DEFAULT NULL,
  `max_length` int(10) unsigned DEFAULT NULL,
  `sort_order` int(10) unsigned NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `condition_field_id` bigint(20) unsigned DEFAULT NULL,
  `condition_operator` enum('equals','not_equals','in','contains','filled','empty') DEFAULT NULL,
  `condition_value` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_visit_field_key` (`form_id`,`field_key`),
  KEY `ix_visit_fields_order` (`form_id`,`sort_order`),
  KEY `fk_visit_fields_condition` (`condition_field_id`),
  CONSTRAINT `fk_visit_fields_condition` FOREIGN KEY (`condition_field_id`) REFERENCES `visit_form_fields` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_visit_fields_form` FOREIGN KEY (`form_id`) REFERENCES `visit_forms` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=110 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `visit_form_fields` (`id`, `form_id`, `field_key`, `label`, `field_type`, `options`, `placeholder`, `help_text`, `is_required`, `min_value`, `max_value`, `max_length`, `sort_order`, `is_active`, `condition_field_id`, `condition_operator`, `condition_value`, `created_at`, `updated_at`) VALUES (1,1,'account_context','Account details (auto-filled from the allocation)','section',NULL,NULL,'Branch, BC Supervisor, borrower, father name, address, loan account, loan type, outstanding, overdue and NPA date are filled in by the app.',0,NULL,NULL,NULL,10,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(2,1,'visit_status','Visit status','dropdown','Customer met\nFamily met\nPhone contact only\nHouse locked\nCustomer not available\nAddress not found\nDeceased\nShifted\nRefused to pay\nOther',NULL,NULL,1,NULL,NULL,NULL,20,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(3,1,'customer_available','Customer available','yes_no',NULL,NULL,NULL,1,NULL,NULL,NULL,30,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(4,1,'family_met','Family member met','yes_no',NULL,NULL,NULL,0,NULL,NULL,NULL,40,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(5,1,'phone_contact','Contacted over phone','yes_no',NULL,NULL,NULL,0,NULL,NULL,NULL,50,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(6,1,'house_locked','House locked','yes_no',NULL,NULL,NULL,0,NULL,NULL,NULL,60,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(7,1,'is_alive','Borrower alive','yes_no',NULL,NULL,'Record \"No\" only when confirmed by the family.',0,NULL,NULL,NULL,70,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(8,1,'current_address','Current address','textarea',NULL,NULL,'Fill in when the borrower has shifted.',0,NULL,NULL,NULL,80,1,3,'equals','No','2026-08-19 07:56:34','2026-08-19 07:56:34'),
(9,1,'occupation','Present occupation','text',NULL,NULL,NULL,0,NULL,NULL,NULL,90,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(10,1,'recovery_section','Recovery assessment','section',NULL,NULL,NULL,0,NULL,NULL,NULL,100,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(11,1,'recovery_possibility','Recovery possibility','dropdown','High\nMedium\nLow\nNil',NULL,NULL,1,NULL,NULL,NULL,110,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(12,1,'promise_amount','Promise amount','decimal',NULL,NULL,'Leave blank when the customer gave no promise.',0,NULL,NULL,NULL,120,1,3,'equals','Yes','2026-08-19 07:56:34','2026-08-19 07:56:34'),
(13,1,'promise_date','Promise date','date',NULL,NULL,NULL,0,NULL,NULL,NULL,130,1,3,'equals','Yes','2026-08-19 07:56:34','2026-08-19 07:56:34'),
(14,1,'reason','Reason for non-payment','textarea',NULL,NULL,NULL,0,NULL,NULL,NULL,140,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(15,1,'recommendation','BC Supervisor recommendation','textarea',NULL,NULL,NULL,0,NULL,NULL,NULL,150,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(16,1,'remarks','Remarks','remarks',NULL,NULL,NULL,1,NULL,NULL,NULL,160,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(17,1,'evidence_section','Evidence','section',NULL,NULL,NULL,0,NULL,NULL,NULL,170,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(18,1,'gps','Visit location','gps',NULL,NULL,'Captured automatically when the visit starts.',1,NULL,NULL,NULL,180,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(19,1,'photo','Photographs','photo',NULL,NULL,'Customer / house / shop / land / document.',1,NULL,NULL,NULL,190,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(20,1,'borrower_signature','Borrower signature','signature',NULL,NULL,NULL,0,NULL,NULL,NULL,200,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(21,1,'supervisor_signature','BC Supervisor signature','signature',NULL,NULL,NULL,0,NULL,NULL,NULL,210,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(22,2,'case_context','1-3. General information, borrower and loan account','section',NULL,NULL,'Visit date and time, branch, regional office, zone, SP/CBC name, BC Agent name, BC code, DRA ID, district, village and GPS are recorded automatically. Borrower name, father/husband name, gender, date of birth, mobile, Aadhaar (last 4), PAN, full address, loan account number, CIF, loan type, sanction date and limit, drawing power, outstanding, interest overdue, overdue, NPA date and asset classification come from the loan book. Correct anything that is wrong in the field below.',0,NULL,NULL,NULL,10,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(23,2,'alternate_mobile','Alternate mobile (if found in the field)','text',NULL,NULL,NULL,0,NULL,NULL,NULL,20,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(24,2,'ots_section','4. KRM OTS details','section',NULL,NULL,NULL,0,NULL,NULL,NULL,30,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(25,2,'ots_eligible','Eligible for KRM OTS','yes_no',NULL,NULL,NULL,1,NULL,NULL,NULL,40,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(26,2,'scheme','Applicable scheme','dropdown','KRM OTS\nGeneral OTS\nOther',NULL,NULL,0,NULL,NULL,NULL,50,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(27,2,'scheme_other','Other scheme','text',NULL,NULL,NULL,0,NULL,NULL,NULL,60,1,26,'equals','Other','2026-08-19 07:56:34','2026-08-19 07:56:34'),
(28,2,'ots_amount','Proposed settlement','decimal',NULL,NULL,'Cannot be more than the outstanding balance.',0,NULL,NULL,NULL,70,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(29,2,'borrower_share','Borrower\'s share','decimal',NULL,NULL,NULL,0,NULL,NULL,NULL,80,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(30,2,'initial_deposit_required','Initial deposit required','decimal',NULL,NULL,NULL,0,NULL,NULL,NULL,90,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(31,2,'customer_response','Customer response','dropdown','Agreed for OTS\nRequested Time\nFinancial Difficulty\nRefused OTS\nNot Eligible',NULL,NULL,1,NULL,NULL,NULL,100,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(32,2,'promise_date','Expected deposit date','date',NULL,NULL,NULL,0,NULL,NULL,NULL,110,1,31,'equals','Agreed for OTS','2026-08-19 07:56:34','2026-08-19 07:56:34'),
(33,2,'verification_section','6. Physical verification','section',NULL,NULL,NULL,0,NULL,NULL,NULL,120,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(34,2,'customer_available','Borrower met','yes_no',NULL,NULL,NULL,1,NULL,NULL,NULL,130,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(35,2,'family_met','Family member met','yes_no',NULL,NULL,NULL,0,NULL,NULL,NULL,140,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(36,2,'house_locked','House locked','yes_no',NULL,NULL,NULL,0,NULL,NULL,NULL,150,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(37,2,'is_alive','Borrower alive','yes_no',NULL,NULL,'Record \"No\" only when confirmed by the family.',0,NULL,NULL,NULL,160,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(38,2,'address_shifted','Current address — borrower has shifted','yes_no',NULL,NULL,'Answer \"No\" when the borrower is still at the recorded address.',0,NULL,NULL,NULL,170,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(39,2,'current_address','New address','textarea',NULL,NULL,NULL,0,NULL,NULL,NULL,180,1,38,'equals','Yes','2026-08-19 07:56:34','2026-08-19 07:56:34'),
(40,2,'phone_contact','Mobile contacted','yes_no',NULL,NULL,NULL,0,NULL,NULL,NULL,190,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(41,2,'residence_verified','Residence verification confirmed','yes_no',NULL,NULL,NULL,0,NULL,NULL,NULL,200,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(42,2,'neighbour_verified','Neighbour verification conducted','yes_no',NULL,NULL,NULL,0,NULL,NULL,NULL,210,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(43,2,'occupation','Current occupation','dropdown','Agriculture\nDairy\nBusiness\nLabour\nService\nOther',NULL,NULL,0,NULL,NULL,NULL,220,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(44,2,'documents_section','7. Documents verified','section',NULL,NULL,NULL,0,NULL,NULL,NULL,230,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(45,2,'documents_verified','Documents verified','checkbox','Aadhaar Card\nPAN Card\nPassbook\nLand Record\nKhatauni\nElectricity Bill\nPhotograph\nMobile Verified\nOTS Consent Letter\nOther',NULL,'Tick every document actually seen.',0,NULL,NULL,NULL,240,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(46,2,'documents_other','Other document','text',NULL,NULL,NULL,0,NULL,NULL,NULL,250,1,45,'contains','Other','2026-08-19 07:56:34','2026-08-19 07:56:34'),
(47,2,'observations_section','8. BC Agent observations','section',NULL,NULL,NULL,0,NULL,NULL,NULL,260,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(48,2,'remarks','Observations','remarks',NULL,NULL,'What was seen and said in the field, in your own words.',1,NULL,NULL,NULL,270,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(49,2,'recommendation_section','9. Recommendation','section',NULL,NULL,NULL,0,NULL,NULL,NULL,280,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(50,2,'ots_recommendation','KRM OTS recommendation','dropdown','OTS Proposal Recommended\nFollow-up Required\nCustomer Refused\nNot Eligible',NULL,NULL,1,NULL,NULL,NULL,290,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(51,2,'recommendation','General recommendation','textarea',NULL,NULL,NULL,0,NULL,NULL,NULL,300,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(52,2,'evidence_section','10. Evidence attached','section',NULL,NULL,NULL,0,NULL,NULL,NULL,310,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(53,2,'gps','GPS location','gps',NULL,NULL,'Captured automatically when the visit starts.',1,NULL,NULL,NULL,320,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(54,2,'photo','Photographs','photo',NULL,NULL,'Borrower, house, land, Aadhaar copy, passbook copy as applicable.',1,NULL,NULL,NULL,330,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(55,2,'evidence_attached','Evidence attached','checkbox','Borrower Photograph\nHouse Photograph\nLand Photograph\nAadhaar Copy\nPassbook Copy\nGPS Location\nOTS Consent\nOther',NULL,NULL,0,NULL,NULL,NULL,340,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(56,2,'evidence_other','Other evidence','text',NULL,NULL,NULL,0,NULL,NULL,NULL,350,1,55,'contains','Other','2026-08-19 07:56:34','2026-08-19 07:56:34'),
(57,2,'declaration_section','11. Declaration','section',NULL,NULL,'I hereby certify that the information contained in this report has been collected and verified during my personal physical field visit through direct interaction with the borrower and/or other reliable local sources, wherever applicable. The details recorded herein represent the factual position observed and verified during the visit and have been documented fairly, accurately, objectively, and in good faith to the best of my knowledge and belief. I further certify that no information has been intentionally concealed, altered, or misrepresented. The field verification has been conducted strictly in accordance with the applicable Reserve Bank of India (RBI) guidelines, the Bank\'s extant policies, operational instructions, the Fair Practices Code, and the prescribed Code of Conduct governing field verification, customer interaction, and recovery-related activities. This report is submitted solely for the purpose of assessment, verification, recovery follow-up, and/or renewal processing, as applicable, and shall be subject to verification and acceptance by the Bank.',0,NULL,NULL,NULL,360,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(58,2,'declaration_accepted','I accept the declaration above','yes_no',NULL,NULL,'The report cannot be submitted without accepting it.',1,NULL,NULL,NULL,370,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(59,2,'certification_section','12. Certification','section',NULL,NULL,'Your name, BC code, DRA ID and mobile number are printed from your profile. The Admin/Supervisor countersigns when the report is approved.',0,NULL,NULL,NULL,380,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(60,2,'borrower_signature','Borrower signature','signature',NULL,NULL,NULL,0,NULL,NULL,NULL,390,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(61,2,'supervisor_signature','BC Agent signature','signature',NULL,NULL,NULL,0,NULL,NULL,NULL,400,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(62,2,'status_section','13. Final report status','section',NULL,NULL,NULL,0,NULL,NULL,NULL,410,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(63,2,'ots_final_status','Final status','dropdown','Customer Contacted\nCustomer Verified\nOTS Accepted\nOTS Rejected\nInitial Deposit Received\nOTS Closed\nFollow-up Required',NULL,NULL,0,NULL,NULL,NULL,420,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(64,3,'case_context','1-3. General information, borrower and loan account','section',NULL,NULL,'Visit date and time, branch, regional office, zone, SP/CBC name, BC Agent name, BC code, DRA ID, district, village and GPS are recorded automatically. Borrower name, father/husband name, gender, date of birth, mobile, Aadhaar (last 4), PAN, full address, loan account number, CIF, loan type, sanction date and limit, drawing power, outstanding, interest overdue, overdue, NPA date and asset classification come from the loan book. Correct anything that is wrong in the field below.',0,NULL,NULL,NULL,10,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(65,3,'alternate_mobile','Alternate mobile (if found in the field)','text',NULL,NULL,NULL,0,NULL,NULL,NULL,20,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(66,3,'renewal_section','5. CKCC OD-2 renewal details','section',NULL,NULL,NULL,0,NULL,NULL,NULL,30,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(67,3,'renewal_eligible','Eligible for renewal','yes_no',NULL,NULL,NULL,1,NULL,NULL,NULL,40,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(68,3,'renewal_due_bucket','Renewal due','dropdown','Within 30 Days\nWithin 15 Days\nWithin 7 Days\nOverdue',NULL,NULL,0,NULL,NULL,NULL,50,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(69,3,'renewal_due_date','Renewal due date','date',NULL,NULL,NULL,0,NULL,NULL,NULL,60,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(70,3,'expected_npa_date','Expected NPA date','date',NULL,NULL,NULL,0,NULL,NULL,NULL,70,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(71,3,'days_remaining','Days remaining','number',NULL,NULL,NULL,0,NULL,NULL,NULL,80,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(72,3,'kyc_status','KYC status','dropdown','Complete\nPending',NULL,NULL,0,NULL,NULL,NULL,90,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(73,3,'aadhaar_seeded','Aadhaar seeded','yes_no',NULL,NULL,NULL,0,NULL,NULL,NULL,100,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(74,3,'mobile_linked','Mobile linked','yes_no',NULL,NULL,NULL,0,NULL,NULL,NULL,110,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(75,3,'aadhaar_authentication','Aadhaar authentication','dropdown','Completed\nPending',NULL,NULL,0,NULL,NULL,NULL,120,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(76,3,'renewal_consent','Borrower willing to renew','yes_no',NULL,NULL,NULL,1,NULL,NULL,NULL,130,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(77,3,'renewal_form_signed','Renewal form signed','yes_no',NULL,NULL,NULL,0,NULL,NULL,NULL,140,1,76,'equals','Yes','2026-08-19 07:56:34','2026-08-19 07:56:34'),
(78,3,'biometrics_completed','Biometrics completed','yes_no',NULL,NULL,NULL,0,NULL,NULL,NULL,150,1,76,'equals','Yes','2026-08-19 07:56:34','2026-08-19 07:56:34'),
(79,3,'verification_section','6. Physical verification','section',NULL,NULL,NULL,0,NULL,NULL,NULL,160,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(80,3,'customer_available','Borrower met','yes_no',NULL,NULL,NULL,1,NULL,NULL,NULL,170,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(81,3,'family_met','Family member met','yes_no',NULL,NULL,NULL,0,NULL,NULL,NULL,180,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(82,3,'house_locked','House locked','yes_no',NULL,NULL,NULL,0,NULL,NULL,NULL,190,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(83,3,'is_alive','Borrower alive','yes_no',NULL,NULL,'Record \"No\" only when confirmed by the family.',0,NULL,NULL,NULL,200,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(84,3,'address_shifted','Current address — borrower has shifted','yes_no',NULL,NULL,'Answer \"No\" when the borrower is still at the recorded address.',0,NULL,NULL,NULL,210,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(85,3,'current_address','New address','textarea',NULL,NULL,NULL,0,NULL,NULL,NULL,220,1,84,'equals','Yes','2026-08-19 07:56:34','2026-08-19 07:56:34'),
(86,3,'phone_contact','Mobile contacted','yes_no',NULL,NULL,NULL,0,NULL,NULL,NULL,230,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(87,3,'residence_verified','Residence verification confirmed','yes_no',NULL,NULL,NULL,0,NULL,NULL,NULL,240,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(88,3,'neighbour_verified','Neighbour verification conducted','yes_no',NULL,NULL,NULL,0,NULL,NULL,NULL,250,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(89,3,'occupation','Current occupation','dropdown','Agriculture\nDairy\nBusiness\nLabour\nService\nOther',NULL,NULL,0,NULL,NULL,NULL,260,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(90,3,'documents_section','7. Documents verified','section',NULL,NULL,NULL,0,NULL,NULL,NULL,270,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(91,3,'documents_verified','Documents verified','checkbox','Aadhaar Card\nPAN Card\nPassbook\nLand Record\nKhatauni\nElectricity Bill\nPhotograph\nMobile Verified\nRenewal Form\nOther',NULL,'Tick every document actually seen.',0,NULL,NULL,NULL,280,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(92,3,'documents_other','Other document','text',NULL,NULL,NULL,0,NULL,NULL,NULL,290,1,91,'contains','Other','2026-08-19 07:56:34','2026-08-19 07:56:34'),
(93,3,'observations_section','8. BC Agent observations','section',NULL,NULL,NULL,0,NULL,NULL,NULL,300,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(94,3,'remarks','Observations','remarks',NULL,NULL,'What was seen and said in the field, in your own words.',1,NULL,NULL,NULL,310,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(95,3,'recommendation_section','9. Recommendation','section',NULL,NULL,NULL,0,NULL,NULL,NULL,320,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(96,3,'renewal_recommendation','CKCC renewal recommendation','dropdown','Renewal Immediately Recommended\nDocuments Complete\nPending Documents\nCustomer Not Interested\nBranch Follow-up Required',NULL,NULL,1,NULL,NULL,NULL,330,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(97,3,'recommendation','General recommendation','textarea',NULL,NULL,NULL,0,NULL,NULL,NULL,340,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(98,3,'evidence_section','10. Evidence attached','section',NULL,NULL,NULL,0,NULL,NULL,NULL,350,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(99,3,'gps','GPS location','gps',NULL,NULL,'Captured automatically when the visit starts.',1,NULL,NULL,NULL,360,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(100,3,'photo','Photographs','photo',NULL,NULL,'Borrower, house, land, Aadhaar copy, passbook copy as applicable.',1,NULL,NULL,NULL,370,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(101,3,'evidence_attached','Evidence attached','checkbox','Borrower Photograph\nHouse Photograph\nLand Photograph\nAadhaar Copy\nPassbook Copy\nGPS Location\nRenewal Form\nOther',NULL,NULL,0,NULL,NULL,NULL,380,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(102,3,'evidence_other','Other evidence','text',NULL,NULL,NULL,0,NULL,NULL,NULL,390,1,101,'contains','Other','2026-08-19 07:56:34','2026-08-19 07:56:34'),
(103,3,'declaration_section','11. Declaration','section',NULL,NULL,'I hereby certify that the information contained in this report has been collected and verified during my personal physical field visit through direct interaction with the borrower and/or other reliable local sources, wherever applicable. The details recorded herein represent the factual position observed and verified during the visit and have been documented fairly, accurately, objectively, and in good faith to the best of my knowledge and belief. I further certify that no information has been intentionally concealed, altered, or misrepresented. The field verification has been conducted strictly in accordance with the applicable Reserve Bank of India (RBI) guidelines, the Bank\'s extant policies, operational instructions, the Fair Practices Code, and the prescribed Code of Conduct governing field verification, customer interaction, and recovery-related activities. This report is submitted solely for the purpose of assessment, verification, recovery follow-up, and/or renewal processing, as applicable, and shall be subject to verification and acceptance by the Bank.',0,NULL,NULL,NULL,400,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(104,3,'declaration_accepted','I accept the declaration above','yes_no',NULL,NULL,'The report cannot be submitted without accepting it.',1,NULL,NULL,NULL,410,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(105,3,'certification_section','12. Certification','section',NULL,NULL,'Your name, BC code, DRA ID and mobile number are printed from your profile. The Admin/Supervisor countersigns when the report is approved.',0,NULL,NULL,NULL,420,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(106,3,'borrower_signature','Borrower signature','signature',NULL,NULL,NULL,0,NULL,NULL,NULL,430,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(107,3,'supervisor_signature','BC Agent signature','signature',NULL,NULL,NULL,0,NULL,NULL,NULL,440,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(108,3,'status_section','13. Final report status','section',NULL,NULL,NULL,0,NULL,NULL,NULL,450,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(109,3,'renewal_final_status','Final status','dropdown','Customer Contacted\nCustomer Verified\nDocuments Collected\nRenewal Submitted\nRenewal Approved\nPending at Branch\nAccount Became NPA\nFollow-up Required',NULL,NULL,0,NULL,NULL,NULL,460,1,NULL,NULL,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34');
DROP TABLE IF EXISTS `visit_form_values`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `visit_form_values` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `visit_id` bigint(20) unsigned NOT NULL,
  `field_id` bigint(20) unsigned DEFAULT NULL,
  `field_key` varchar(80) NOT NULL,
  `label` varchar(255) DEFAULT NULL,
  `field_type` varchar(30) DEFAULT NULL,
  `value` text DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_visit_value` (`visit_id`,`field_key`),
  KEY `ix_visit_values_field` (`field_id`),
  CONSTRAINT `fk_visit_values_field` FOREIGN KEY (`field_id`) REFERENCES `visit_form_fields` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_visit_values_visit` FOREIGN KEY (`visit_id`) REFERENCES `visits` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `visit_forms`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `visit_forms` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(160) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `visit_type` enum('customer','krm_ots','ckcc_od2') NOT NULL DEFAULT 'customer',
  `version` int(10) unsigned NOT NULL DEFAULT 1,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `is_default` tinyint(1) NOT NULL DEFAULT 0,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_visit_forms_type` (`visit_type`,`is_active`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `visit_forms` (`id`, `name`, `description`, `visit_type`, `version`, `is_active`, `is_default`, `created_by`, `created_at`, `updated_at`) VALUES (1,'Customer Recovery Visit','Default TYPE A form: BC Supervisor customer field visit.','customer',1,1,1,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(2,'KRM OTS Field Visit Verification Report','One Time Settlement field verification. RBI guidelines and Code of Conduct compliant format.','krm_ots',1,1,1,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34'),
(3,'CKCC OD-2 Renewal Field Visit Verification Report','CKCC OD-2 renewal field verification. RBI guidelines and Code of Conduct compliant format.','ckcc_od2',1,1,1,NULL,'2026-08-19 07:56:34','2026-08-19 07:56:34');
DROP TABLE IF EXISTS `visit_gps`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `visit_gps` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `visit_id` bigint(20) unsigned NOT NULL,
  `event` enum('start','form','photo','submit') NOT NULL DEFAULT 'start',
  `latitude` decimal(10,7) NOT NULL,
  `longitude` decimal(10,7) NOT NULL,
  `accuracy` decimal(8,2) DEFAULT NULL,
  `altitude` decimal(8,2) DEFAULT NULL,
  `speed` decimal(8,2) DEFAULT NULL,
  `provider` varchar(40) DEFAULT NULL,
  `is_mock` tinyint(1) NOT NULL DEFAULT 0,
  `address` varchar(255) DEFAULT NULL,
  `captured_at` datetime DEFAULT NULL,
  `device_time` datetime DEFAULT NULL,
  `server_time` datetime DEFAULT NULL,
  `is_valid` tinyint(1) NOT NULL DEFAULT 1,
  `validation_note` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_visit_gps_visit` (`visit_id`,`event`),
  CONSTRAINT `fk_visit_gps_visit` FOREIGN KEY (`visit_id`) REFERENCES `visits` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `visit_photos`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `visit_photos` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `visit_id` bigint(20) unsigned NOT NULL,
  `photo_type` enum('customer','house','shop','land','document','selfie','other') NOT NULL DEFAULT 'other',
  `file_path` varchar(255) NOT NULL,
  `file_name` varchar(190) NOT NULL,
  `mime_type` varchar(60) NOT NULL DEFAULT 'image/jpeg',
  `file_size` bigint(20) unsigned NOT NULL DEFAULT 0,
  `width` int(10) unsigned DEFAULT NULL,
  `height` int(10) unsigned DEFAULT NULL,
  `sha256` char(64) DEFAULT NULL,
  `latitude` decimal(10,7) DEFAULT NULL,
  `longitude` decimal(10,7) DEFAULT NULL,
  `accuracy` decimal(8,2) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `captured_at` datetime DEFAULT NULL,
  `watermarked` tinyint(1) NOT NULL DEFAULT 0,
  `caption` varchar(255) DEFAULT NULL,
  `uploaded_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_visit_photo_hash` (`visit_id`,`sha256`),
  KEY `ix_visit_photos_visit` (`visit_id`,`photo_type`),
  CONSTRAINT `fk_visit_photos_visit` FOREIGN KEY (`visit_id`) REFERENCES `visits` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `visits`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `visits` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) NOT NULL,
  `loan_account_id` bigint(20) unsigned NOT NULL,
  `bc_supervisor_id` bigint(20) unsigned NOT NULL,
  `branch_id` bigint(20) unsigned NOT NULL,
  `form_id` bigint(20) unsigned DEFAULT NULL,
  `visit_type` enum('customer','krm_ots','ckcc_od2','recovery_followup','pre_npa','post_npa','other') NOT NULL DEFAULT 'customer',
  `visit_type_other` varchar(120) DEFAULT NULL,
  `visit_date` date NOT NULL,
  `visit_time` time DEFAULT NULL,
  `started_at` datetime DEFAULT NULL,
  `submitted_at` datetime DEFAULT NULL,
  `server_received_at` datetime DEFAULT NULL,
  `client_created_at` datetime DEFAULT NULL,
  `visit_status` enum('customer_met','family_met','phone_contact','house_locked','not_available','address_not_found','deceased','shifted','refused','other') DEFAULT NULL,
  `customer_available` tinyint(1) DEFAULT NULL,
  `family_met` tinyint(1) DEFAULT NULL,
  `phone_contact` tinyint(1) DEFAULT NULL,
  `house_locked` tinyint(1) DEFAULT NULL,
  `is_alive` tinyint(1) DEFAULT NULL,
  `current_address` varchar(500) DEFAULT NULL,
  `address_shifted` tinyint(1) DEFAULT NULL,
  `occupation` varchar(160) DEFAULT NULL,
  `residence_verified` tinyint(1) DEFAULT NULL,
  `neighbour_verified` tinyint(1) DEFAULT NULL,
  `documents_verified` varchar(500) DEFAULT NULL,
  `documents_other` varchar(160) DEFAULT NULL,
  `evidence_attached` varchar(500) DEFAULT NULL,
  `evidence_other` varchar(160) DEFAULT NULL,
  `recovery_possibility` enum('high','medium','low','nil') DEFAULT NULL,
  `recommendation` varchar(500) DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `status` enum('draft','submitted','late_pending','approved','rejected') NOT NULL DEFAULT 'submitted',
  `is_late` tinyint(1) NOT NULL DEFAULT 0,
  `late_reason` varchar(255) DEFAULT NULL,
  `approved_by` bigint(20) unsigned DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `gps_verified` tinyint(1) NOT NULL DEFAULT 0,
  `gps_note` varchar(255) DEFAULT NULL,
  `photo_count` int(10) unsigned NOT NULL DEFAULT 0,
  `borrower_signature` varchar(255) DEFAULT NULL,
  `supervisor_signature` varchar(255) DEFAULT NULL,
  `declaration_accepted` tinyint(1) NOT NULL DEFAULT 0,
  `declared_at` datetime DEFAULT NULL,
  `verifier_signature` varchar(255) DEFAULT NULL,
  `device_id` bigint(20) unsigned DEFAULT NULL,
  `sync_batch_id` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_visits_uuid` (`uuid`),
  KEY `ix_visits_account` (`loan_account_id`),
  KEY `ix_visits_bc_date` (`bc_supervisor_id`,`visit_date`),
  KEY `ix_visits_branch_date` (`branch_id`,`visit_date`),
  KEY `ix_visits_status` (`status`),
  KEY `ix_visits_type` (`visit_type`),
  KEY `fk_visits_form` (`form_id`),
  KEY `fk_visits_device` (`device_id`),
  KEY `fk_visits_batch` (`sync_batch_id`),
  CONSTRAINT `fk_visits_account` FOREIGN KEY (`loan_account_id`) REFERENCES `loan_accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_visits_batch` FOREIGN KEY (`sync_batch_id`) REFERENCES `sync_batches` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_visits_bc` FOREIGN KEY (`bc_supervisor_id`) REFERENCES `bc_supervisors` (`id`),
  CONSTRAINT `fk_visits_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `fk_visits_device` FOREIGN KEY (`device_id`) REFERENCES `devices` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_visits_form` FOREIGN KEY (`form_id`) REFERENCES `visit_forms` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

SET FOREIGN_KEY_CHECKS = 1;

-- End of LRMS installation.
